### ISSUE TITLE
JSON.minify is not a function

### ISSUE THREAD

**Issue by thomastuts** [pugjs/jade-lint#48]
I'm currently using [gulp-jade-lint](https://github.com/emartech/gulp-jade-lint) to lint our Jade files. When I run the task, I'm getting this error:

```
[08:00:21] Starting 'lint:jade'...
[08:00:21] 'lint:jade' errored after 59 ms
[08:00:21] TypeError in plugin 'gulp-jade-lint'
Message:
    JSON.minify is not a function
```

Using the standalone jade-lint CLI, the linting *does* work properly. After some digging, I think I found out the cause: 

* `gulp-jade-lint` [instantiates a new JadeLint](https://github.com/emartech/gulp-jade-lint/blob/31f7413eb9b4fc20ec307aa189e7b174475afce7/index.js#L27)
* The `"main"` field in your `package.json` loads the `lib/linter.js` file
* This file [uses JSON.minify](https://github.com/benedfit/jade-lint/blob/8465ce1496e9397263b442209ede9e2989ee4e5f/lib/linter.js#L87)
* This throws an error, because `JSON.minify` is undefined at this point. The only place where you [define JSON.minify is in `lib/config-file.js`](https://github.com/benedfit/jade-lint/blob/1e2d6b08995ddf03c503bfffc617c85b86c0ccc2/lib/config-file.js#L7), which I assume does not get loaded when using the `lib/linter.js` file directly

This can be fixed by instantiating `JSON.minify` in the `lib/linter.js` file as well. I just tested this and it does work like it should, but I'm not sure if this is the way to fix it, or if this is even a problem on `jade-lint`'s end. If it is, let me know if you want me to send over a PR. Thanks!

**Comment by benedfit** [comment]
Hi, and thanks for raising. I've raised an issue on `guld-jade-lint` too (https://github.com/emartech/gulp-jade-lint/issues/2) and we'll get to the bottom of it

**Comment by blacksonic** [comment]
Can we live without JSON.minify? As i see it is not even necessary.

**Comment by benedfit** [comment]
Very true. It was put in as a convenience should anyone wish to have comments in their config files. But I'll take it out

**Comment by benedfit** [comment]
It's been removed in v2.1.0

**Comment by thomastuts** [comment]
Awesome, thanks for the super quick response!
